# This configuration does not include a processing node
# Which makes for faster setup times
version: '2.1'

services:
  node-odm-1:
    image: opendronemap/nodeodm
    container_name: webodm-node-odm-1
    ports:
      - "3000:3201"
    restart: unless-stopped
    oom_score_adj: 500
    networks:
      - dokploy-network
  node-odm-2:
    image: opendronemap/nodeodm
    container_name: webodm-node-odm-2
    ports:
      - "3000:3203"
    restart: unless-stopped
    oom_score_adj: 500
    networks:
      - dokploy-network
  node-odm-3:
    image: opendronemap/nodeodm
    container_name: webodm-node-odm-3
    ports:
      - "3000:3203"
    restart: unless-stopped
    oom_score_adj: 500
    networks:
      - dokploy-network

 
networks:
  dokploy-network:
    external: true
    name: dokploy-network